name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: savrinalif/digital-clock:latest, savrinalif/digital-clock:${{ github.run_number }}

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Login to DigitalOcean
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}

      - name: Pull Docker Image on DigitalOcean
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          command: docker pull savrinalif/digital-clock:${{ github.run_number }}

      - name: Stop and Delete Existing Container
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          command: docker rm -f digital-clock || true

      - name: Run Docker Container
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          command: docker run -d --name digital-clock --network nginx-proxy-manager_default savrinalif/digital-clock:${{ github.run_number }}