name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: savrinalif/digital-clock:latest, savrinalif/digital-clock:${{ github.run_number }}

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Login to DigitalOcean
        uses: appleboy/ssh-action@v0.0.6
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}

      - name: Pull Docker Image on DigitalOcean
        run: ssh root@${{ secrets.HOST }} "docker pull savrinalif/digital-clock:${{ github.run_number }}"

      - name: Run Docker Container
        run: ssh root@${{ secrets.HOST }} "docker run -d --name digital-clock --network nginx-proxy-manager_default savrinalif/digital-clock:${{ github.run_number }}"